/* eslint-disable */
// @ts-nocheck
// This file is automatically generated by TanStack Router

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as RoomIdImport } from './routes/room.$id';
import { Route as PlayIdImport } from './routes/play.$id';

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const RoomIdRoute = RoomIdImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRoute,
} as any);

const PlayIdRoute = PlayIdImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRoute,
} as any);

export const routeTree = rootRoute._addFileChildren({
  IndexRoute,
  RoomIdRoute,
  PlayIdRoute,
});

